// ============================================================
// MOMENTUM — Complete Roadmap Data
// 52 topics across 4 phases, with subtopics, resources, LC problems
// ============================================================

export type TopicStatus = "NOT_STARTED" | "IN_PROGRESS" | "DONE";
export type PhaseNumber = 1 | 2 | 3 | 4;

export interface LCProblem {
  id: number;
  title: string;
  difficulty: "Easy" | "Medium" | "Hard";
}

export interface Resource {
  title: string;
  url: string;
  type: "youtube" | "website" | "book" | "course";
}

export interface RoadmapTopic {
  id: string;
  phase: PhaseNumber;
  category: string;
  title: string;
  estimatedHours: number;
  subtopics: string[];
  resources: Resource[];
  leetcode: LCProblem[];
}

export const PHASE_META: Record<PhaseNumber, { label: string; dateRange: string; target: string; color: string }> = {
  1: { label: "FOUNDATION", dateRange: "Mar 23 – Jun 30, 2026", target: "100 LC Easy · First internship · 3 projects", color: "#3b82f6" },
  2: { label: "SKILL BUILD", dateRange: "Jul 1 – Dec 31, 2026", target: "400 LC total · Use cousin referrals Oct 2026", color: "#a855f7" },
  3: { label: "PEAK PREP", dateRange: "Jan 1 – May 31, 2027", target: "600 LC · Strong internship · System Design", color: "#f97316" },
  4: { label: "APPLICATION BLITZ", dateRange: "Jun 1 – Oct 31, 2027", target: "750+ LC · 200 applications · ₹60L offer", color: "#ef4444" },
};

export const ROADMAP_TOPICS: RoadmapTopic[] = [
  // ═══════════════════════════════════════════════════════════
  // PHASE 1: FOUNDATION
  // ═══════════════════════════════════════════════════════════

  // ── PYTHON MASTERY ──────────────────────────────────────────
  {
    id: "py-basics",
    phase: 1,
    category: "Python Mastery",
    title: "Python Basics",
    estimatedHours: 15,
    subtopics: [
      "Variables, data types, type casting",
      "Strings and string methods",
      "Lists, tuples, sets, dictionaries",
      "Conditional statements (if/elif/else)",
      "Loops (for, while, break, continue)",
      "Functions, *args, **kwargs",
      "Lambda functions",
      "List/dict/set comprehensions",
      "File I/O (read, write, append)",
      "Exception handling (try/except/finally)",
    ],
    resources: [
      { title: "learnpython.org", url: "https://learnpython.org", type: "website" },
      { title: "CodeWithHarry Python playlist", url: "https://www.youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg", type: "youtube" },
      { title: "Python Crash Course (book, ch 1-8)", url: "https://nostarch.com/pythoncrashcourse2e", type: "book" },
    ],
    leetcode: [
      { id: 1, title: "Two Sum", difficulty: "Easy" },
      { id: 9, title: "Palindrome Number", difficulty: "Easy" },
      { id: 344, title: "Reverse String", difficulty: "Easy" },
      { id: 412, title: "FizzBuzz", difficulty: "Easy" },
    ],
  },
  {
    id: "py-oop",
    phase: 1,
    category: "Python Mastery",
    title: "Object Oriented Programming",
    estimatedHours: 12,
    subtopics: [
      "Classes and objects",
      "__init__, self, instance variables",
      "Instance vs class methods",
      "Inheritance and super()",
      "Encapsulation (private/public)",
      "Polymorphism and method overriding",
      "Dunder methods (__str__, __len__, __eq__)",
      "Abstract classes",
    ],
    resources: [
      { title: "Corey Schafer OOP playlist", url: "https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc", type: "youtube" },
      { title: "Real Python OOP tutorials", url: "https://realpython.com/python3-object-oriented-programming/", type: "website" },
    ],
    leetcode: [
      { id: 1603, title: "Design Parking System", difficulty: "Easy" },
      { id: 706, title: "Design HashMap", difficulty: "Easy" },
    ],
  },
  {
    id: "py-advanced",
    phase: 1,
    category: "Python Mastery",
    title: "Python Advanced",
    estimatedHours: 13,
    subtopics: [
      "Modules and packages",
      "Virtual environments (venv)",
      "pip and requirements.txt",
      "Decorators",
      "Generators and iterators",
      "Context managers (with statement)",
      "Regular expressions (re module)",
      "datetime module",
      "os and sys modules",
    ],
    resources: [
      { title: "Corey Schafer Advanced Python", url: "https://www.youtube.com/c/Coreyms", type: "youtube" },
      { title: "Real Python advanced tutorials", url: "https://realpython.com/tutorials/advanced/", type: "website" },
    ],
    leetcode: [],
  },

  // ── DATA STRUCTURES & ALGORITHMS ───────────────────────────
  {
    id: "dsa-arrays",
    phase: 1,
    category: "DSA",
    title: "Arrays & Strings",
    estimatedHours: 20,
    subtopics: [
      "Array traversal and manipulation",
      "Sliding window technique",
      "Two pointer technique",
      "Prefix sums",
      "Kadane's algorithm",
      "String manipulation",
      "ASCII and character operations",
    ],
    resources: [
      { title: "NeetCode Arrays playlist", url: "https://www.youtube.com/playlist?list=PLot-Xpze53ldVwtstag2TL4HQhAnC8ATf", type: "youtube" },
      { title: "NeetCode.io arrays section", url: "https://neetcode.io/practice", type: "website" },
    ],
    leetcode: [
      { id: 121, title: "Best Time to Buy and Sell Stock", difficulty: "Easy" },
      { id: 217, title: "Contains Duplicate", difficulty: "Easy" },
      { id: 238, title: "Product of Array Except Self", difficulty: "Medium" },
      { id: 53, title: "Maximum Subarray", difficulty: "Medium" },
      { id: 1, title: "Two Sum", difficulty: "Easy" },
      { id: 242, title: "Valid Anagram", difficulty: "Easy" },
      { id: 49, title: "Group Anagrams", difficulty: "Medium" },
      { id: 14, title: "Longest Common Prefix", difficulty: "Easy" },
      { id: 125, title: "Valid Palindrome", difficulty: "Easy" },
      { id: 151, title: "Reverse Words in String", difficulty: "Medium" },
    ],
  },
  {
    id: "dsa-hashmaps",
    phase: 1,
    category: "DSA",
    title: "Hash Maps & Sets",
    estimatedHours: 12,
    subtopics: [
      "Hash map internals (how hashing works)",
      "Collision handling",
      "Python dict and set operations",
      "Frequency counting pattern",
      "Grouping pattern",
    ],
    resources: [
      { title: "NeetCode Hashing playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
    ],
    leetcode: [
      { id: 1, title: "Two Sum", difficulty: "Easy" },
      { id: 49, title: "Group Anagrams", difficulty: "Medium" },
      { id: 347, title: "Top K Frequent Elements", difficulty: "Medium" },
      { id: 36, title: "Valid Sudoku", difficulty: "Medium" },
      { id: 271, title: "Encode and Decode Strings", difficulty: "Medium" },
      { id: 128, title: "Longest Consecutive Sequence", difficulty: "Medium" },
    ],
  },
  {
    id: "dsa-linkedlist",
    phase: 1,
    category: "DSA",
    title: "Linked Lists",
    estimatedHours: 15,
    subtopics: [
      "Singly linked list implementation",
      "Doubly linked list implementation",
      "Traversal, insertion, deletion",
      "Fast and slow pointer technique",
      "Reversing a linked list",
      "Finding cycles (Floyd's algorithm)",
      "Merge sorted lists",
    ],
    resources: [
      { title: "NeetCode Linked List playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
      { title: "Abdul Bari Linked List", url: "https://www.youtube.com/c/AbdulBari", type: "youtube" },
    ],
    leetcode: [
      { id: 206, title: "Reverse Linked List", difficulty: "Easy" },
      { id: 21, title: "Merge Two Sorted Lists", difficulty: "Easy" },
      { id: 141, title: "Linked List Cycle", difficulty: "Easy" },
      { id: 19, title: "Remove Nth Node From End", difficulty: "Medium" },
      { id: 143, title: "Reorder List", difficulty: "Medium" },
      { id: 146, title: "LRU Cache", difficulty: "Medium" },
    ],
  },
  {
    id: "dsa-stacks",
    phase: 1,
    category: "DSA",
    title: "Stacks & Queues",
    estimatedHours: 15,
    subtopics: [
      "Stack implementation (list-based)",
      "Queue implementation (deque)",
      "Monotonic stack concept",
      "Stack for bracket matching",
      "Queue for BFS",
    ],
    resources: [
      { title: "NeetCode Stack playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
    ],
    leetcode: [
      { id: 20, title: "Valid Parentheses", difficulty: "Easy" },
      { id: 155, title: "Min Stack", difficulty: "Medium" },
      { id: 150, title: "Evaluate Reverse Polish Notation", difficulty: "Medium" },
      { id: 22, title: "Generate Parentheses", difficulty: "Medium" },
      { id: 739, title: "Daily Temperatures", difficulty: "Medium" },
      { id: 853, title: "Car Fleet", difficulty: "Medium" },
      { id: 84, title: "Largest Rectangle in Histogram", difficulty: "Hard" },
    ],
  },
  {
    id: "dsa-binsearch",
    phase: 1,
    category: "DSA",
    title: "Binary Search",
    estimatedHours: 12,
    subtopics: [
      "Classic binary search template",
      "Search in rotated array",
      "Binary search on answer",
      "Left/right boundary binary search",
    ],
    resources: [
      { title: "NeetCode Binary Search playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
    ],
    leetcode: [
      { id: 704, title: "Binary Search", difficulty: "Easy" },
      { id: 74, title: "Search a 2D Matrix", difficulty: "Medium" },
      { id: 875, title: "Koko Eating Bananas", difficulty: "Medium" },
      { id: 153, title: "Find Minimum in Rotated Array", difficulty: "Medium" },
      { id: 33, title: "Search in Rotated Sorted Array", difficulty: "Medium" },
      { id: 981, title: "Time Based Key-Value Store", difficulty: "Medium" },
    ],
  },
  {
    id: "dsa-sorting",
    phase: 1,
    category: "DSA",
    title: "Sorting Algorithms",
    estimatedHours: 15,
    subtopics: [
      "Bubble sort (understand, not use)",
      "Selection sort (understand, not use)",
      "Insertion sort",
      "Merge sort (IMPORTANT — master this)",
      "Quick sort (IMPORTANT — master this)",
      "Counting sort",
      "Python sort() and sorted() internals",
    ],
    resources: [
      { title: "Abdul Bari Sorting", url: "https://www.youtube.com/c/AbdulBari", type: "youtube" },
      { title: "Visualgo.net (visual animations)", url: "https://visualgo.net/en/sorting", type: "website" },
    ],
    leetcode: [
      { id: 75, title: "Sort Colors", difficulty: "Medium" },
      { id: 56, title: "Merge Intervals", difficulty: "Medium" },
      { id: 57, title: "Insert Interval", difficulty: "Medium" },
      { id: 435, title: "Non-overlapping Intervals", difficulty: "Medium" },
      { id: 252, title: "Meeting Rooms", difficulty: "Easy" },
    ],
  },

  // ── GIT & TOOLS ────────────────────────────────────────────
  {
    id: "tools-git",
    phase: 1,
    category: "Dev Tools",
    title: "Git Fundamentals",
    estimatedHours: 8,
    subtopics: [
      "git init, clone, status",
      "git add, commit, push, pull",
      "Branching (git branch, checkout, merge)",
      "Resolving merge conflicts",
      ".gitignore setup",
      "GitHub profile setup",
      "README.md writing (markdown)",
      "Fork and pull request workflow",
    ],
    resources: [
      { title: "The Odin Project Git section", url: "https://www.theodinproject.com/lessons/foundations-git-basics", type: "website" },
      { title: "Atlassian Git tutorials", url: "https://www.atlassian.com/git/tutorials", type: "website" },
      { title: "Git documentation", url: "https://git-scm.com/doc", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "tools-terminal",
    phase: 1,
    category: "Dev Tools",
    title: "Terminal & Linux Basics",
    estimatedHours: 7,
    subtopics: [
      "Navigation (ls, cd, pwd, mkdir, rm)",
      "File operations (cp, mv, cat, nano)",
      "Permissions (chmod, chown)",
      "Process management (ps, kill, top)",
      "Piping and redirection",
      "Shell scripts basics",
    ],
    resources: [
      { title: "MIT Missing Semester", url: "https://missing.csail.mit.edu/", type: "course" },
      { title: "Linux Journey", url: "https://linuxjourney.com/", type: "website" },
    ],
    leetcode: [],
  },

  // ── PROJECTS PHASE 1 ──────────────────────────────────────
  {
    id: "proj-todo",
    phase: 1,
    category: "Projects",
    title: "Project 1: CLI Todo App (Python)",
    estimatedHours: 15,
    subtopics: [
      "Build task add/remove/complete",
      "Save tasks to JSON file",
      "Filter by status",
      "Add due dates",
      "Colorized terminal output (colorama)",
      "Push to GitHub with README",
    ],
    resources: [],
    leetcode: [],
  },
  {
    id: "proj-weather",
    phase: 1,
    category: "Projects",
    title: "Project 2: Weather Dashboard (Python + API)",
    estimatedHours: 20,
    subtopics: [
      "OpenWeatherMap API key setup",
      "requests library for HTTP calls",
      "Parse JSON responses",
      "Display 5-day forecast",
      "Error handling for bad city names",
      "Save search history to file",
      "Deploy as web app using Flask",
    ],
    resources: [],
    leetcode: [],
  },
  {
    id: "proj-scraper",
    phase: 1,
    category: "Projects",
    title: "Project 3: Web Scraper + Data Analyzer",
    estimatedHours: 25,
    subtopics: [
      "BeautifulSoup for HTML parsing",
      "Scrape job listings from Naukri/LinkedIn",
      "Store data in CSV using pandas",
      "Basic data analysis (top skills, salaries)",
      "Visualize with matplotlib",
      "Schedule to run daily (cron/APScheduler)",
    ],
    resources: [],
    leetcode: [],
  },

  // ── CS FUNDAMENTALS ────────────────────────────────────────
  {
    id: "cs-os",
    phase: 1,
    category: "CS Fundamentals",
    title: "Operating Systems",
    estimatedHours: 15,
    subtopics: [
      "Process vs Thread",
      "Concurrency and parallelism",
      "CPU scheduling algorithms",
      "Memory management (paging, segmentation)",
      "Deadlocks (conditions + prevention)",
      "Virtual memory",
      "File systems basics",
    ],
    resources: [
      { title: "Gate Smashers OS playlist", url: "https://www.youtube.com/c/GateSmashers", type: "youtube" },
      { title: "OSTEP (free book)", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/", type: "book" },
    ],
    leetcode: [],
  },
  {
    id: "cs-networks",
    phase: 1,
    category: "CS Fundamentals",
    title: "Computer Networks",
    estimatedHours: 12,
    subtopics: [
      "OSI model (all 7 layers)",
      "TCP vs UDP",
      "HTTP vs HTTPS",
      "DNS resolution process",
      "IP addressing and subnetting basics",
      "REST API concepts (GET/POST/PUT/DELETE)",
      "How the internet works end-to-end",
    ],
    resources: [
      { title: "Gate Smashers Networks", url: "https://www.youtube.com/c/GateSmashers", type: "youtube" },
      { title: "Computer Networking (Kurose & Ross)", url: "https://www.pearson.com/en-us/subject-catalog/p/computer-networking/P200000003334", type: "book" },
    ],
    leetcode: [],
  },
  {
    id: "cs-databases",
    phase: 1,
    category: "CS Fundamentals",
    title: "Databases Basics",
    estimatedHours: 13,
    subtopics: [
      "Relational vs non-relational databases",
      "SQL: SELECT, INSERT, UPDATE, DELETE",
      "JOINs (INNER, LEFT, RIGHT, FULL)",
      "Indexes and why they matter",
      "ACID properties",
      "Normalization (1NF, 2NF, 3NF)",
      "Basic PostgreSQL setup and usage",
    ],
    resources: [
      { title: "Gate Smashers DBMS", url: "https://www.youtube.com/c/GateSmashers", type: "youtube" },
      { title: "SQLZoo.net (interactive)", url: "https://sqlzoo.net/", type: "website" },
      { title: "Mode SQL Tutorial", url: "https://mode.com/sql-tutorial", type: "website" },
    ],
    leetcode: [],
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 2: SKILL BUILD
  // ═══════════════════════════════════════════════════════════

  // ── ADVANCED DSA ──────────────────────────────────────────
  {
    id: "dsa-trees",
    phase: 2,
    category: "Advanced DSA",
    title: "Trees",
    estimatedHours: 25,
    subtopics: [
      "Binary tree traversals (inorder, preorder, postorder, level order)",
      "Binary Search Tree (BST) operations",
      "BST insert, delete, search",
      "Height and diameter of tree",
      "Lowest Common Ancestor (LCA)",
      "Balanced trees concept (AVL intro)",
    ],
    resources: [
      { title: "NeetCode Trees playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
      { title: "Abdul Bari Trees", url: "https://www.youtube.com/c/AbdulBari", type: "youtube" },
    ],
    leetcode: [
      { id: 226, title: "Invert Binary Tree", difficulty: "Easy" },
      { id: 104, title: "Max Depth of Binary Tree", difficulty: "Easy" },
      { id: 543, title: "Diameter of Binary Tree", difficulty: "Easy" },
      { id: 110, title: "Balanced Binary Tree", difficulty: "Easy" },
      { id: 100, title: "Same Tree", difficulty: "Easy" },
      { id: 572, title: "Subtree of Another Tree", difficulty: "Easy" },
      { id: 235, title: "LCA of BST", difficulty: "Medium" },
      { id: 98, title: "BST Validity", difficulty: "Medium" },
      { id: 230, title: "Kth Smallest in BST", difficulty: "Medium" },
      { id: 105, title: "Construct Tree from Preorder+Inorder", difficulty: "Medium" },
      { id: 102, title: "Binary Tree Level Order Traversal", difficulty: "Medium" },
      { id: 199, title: "Binary Tree Right Side View", difficulty: "Medium" },
      { id: 1448, title: "Count Good Nodes in BT", difficulty: "Medium" },
      { id: 297, title: "Serialize and Deserialize BT", difficulty: "Hard" },
    ],
  },
  {
    id: "dsa-tries",
    phase: 2,
    category: "Advanced DSA",
    title: "Tries",
    estimatedHours: 8,
    subtopics: [
      "Trie data structure implementation",
      "Insert and search in trie",
      "Prefix matching",
      "Word search applications",
    ],
    resources: [],
    leetcode: [
      { id: 208, title: "Implement Trie", difficulty: "Medium" },
      { id: 211, title: "Design Add and Search Words", difficulty: "Medium" },
      { id: 212, title: "Word Search II", difficulty: "Hard" },
    ],
  },
  {
    id: "dsa-heaps",
    phase: 2,
    category: "Advanced DSA",
    title: "Heaps & Priority Queues",
    estimatedHours: 15,
    subtopics: [
      "Min heap and max heap concepts",
      "Python heapq module",
      "Heap insert and extract operations",
      "Top K elements pattern",
      "K-way merge pattern",
    ],
    resources: [
      { title: "NeetCode Heap playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
    ],
    leetcode: [
      { id: 215, title: "Kth Largest Element in Array", difficulty: "Medium" },
      { id: 1046, title: "Last Stone Weight", difficulty: "Easy" },
      { id: 973, title: "K Closest Points to Origin", difficulty: "Medium" },
      { id: 621, title: "Task Scheduler", difficulty: "Medium" },
      { id: 355, title: "Design Twitter", difficulty: "Medium" },
      { id: 295, title: "Find Median from Data Stream", difficulty: "Hard" },
    ],
  },
  {
    id: "dsa-graphs",
    phase: 2,
    category: "Advanced DSA",
    title: "Graphs",
    estimatedHours: 30,
    subtopics: [
      "Graph representation (adjacency list vs matrix)",
      "BFS (Breadth First Search)",
      "DFS (Depth First Search)",
      "Cycle detection (directed + undirected)",
      "Topological sort",
      "Union Find (Disjoint Set Union)",
      "Dijkstra's shortest path algorithm",
      "Bellman-Ford algorithm",
      "Minimum spanning tree (Kruskal, Prim)",
    ],
    resources: [
      { title: "NeetCode Graphs playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
      { title: "William Fiset Graph Theory", url: "https://www.youtube.com/c/WilliamFiset-videos", type: "youtube" },
    ],
    leetcode: [
      { id: 200, title: "Number of Islands", difficulty: "Medium" },
      { id: 133, title: "Clone Graph", difficulty: "Medium" },
      { id: 695, title: "Max Area of Island", difficulty: "Medium" },
      { id: 417, title: "Pacific Atlantic Water Flow", difficulty: "Medium" },
      { id: 130, title: "Surrounded Regions", difficulty: "Medium" },
      { id: 994, title: "Rotting Oranges", difficulty: "Medium" },
      { id: 207, title: "Course Schedule", difficulty: "Medium" },
      { id: 210, title: "Course Schedule II", difficulty: "Medium" },
      { id: 684, title: "Redundant Connection", difficulty: "Medium" },
      { id: 323, title: "Number of Connected Components", difficulty: "Medium" },
      { id: 261, title: "Graph Valid Tree", difficulty: "Medium" },
      { id: 127, title: "Word Ladder", difficulty: "Hard" },
      { id: 778, title: "Swim in Rising Water", difficulty: "Hard" },
      { id: 269, title: "Alien Dictionary", difficulty: "Hard" },
    ],
  },
  {
    id: "dsa-dp",
    phase: 2,
    category: "Advanced DSA",
    title: "Dynamic Programming",
    estimatedHours: 35,
    subtopics: [
      "Memoization (top-down DP)",
      "Tabulation (bottom-up DP)",
      "1D DP problems",
      "2D DP problems",
      "Knapsack pattern",
      "Longest Common Subsequence pattern",
      "Fibonacci pattern",
    ],
    resources: [
      { title: "NeetCode DP playlist", url: "https://www.youtube.com/c/NeetCode", type: "youtube" },
      { title: "Aditya Verma DP playlist", url: "https://www.youtube.com/c/AdityaVermaTheProgrammingLord", type: "youtube" },
      { title: "MIT OpenCourseWare DP lectures", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", type: "course" },
    ],
    leetcode: [
      { id: 70, title: "Climbing Stairs", difficulty: "Easy" },
      { id: 746, title: "Min Cost Climbing Stairs", difficulty: "Easy" },
      { id: 198, title: "House Robber", difficulty: "Medium" },
      { id: 213, title: "House Robber II", difficulty: "Medium" },
      { id: 5, title: "Longest Palindromic Substring", difficulty: "Medium" },
      { id: 647, title: "Palindromic Substrings", difficulty: "Medium" },
      { id: 91, title: "Decode Ways", difficulty: "Medium" },
      { id: 322, title: "Coin Change", difficulty: "Medium" },
      { id: 152, title: "Maximum Product Subarray", difficulty: "Medium" },
      { id: 139, title: "Word Break", difficulty: "Medium" },
      { id: 416, title: "Partition Equal Subset Sum", difficulty: "Medium" },
      { id: 1143, title: "Longest Common Subsequence", difficulty: "Medium" },
      { id: 72, title: "Edit Distance", difficulty: "Medium" },
      { id: 115, title: "Distinct Subsequences", difficulty: "Hard" },
      { id: 97, title: "Interleaving String", difficulty: "Medium" },
      { id: 300, title: "Longest Increasing Subsequence", difficulty: "Medium" },
      { id: 309, title: "Buy and Sell Stock with Cooldown", difficulty: "Medium" },
    ],
  },
  {
    id: "dsa-backtracking",
    phase: 2,
    category: "Advanced DSA",
    title: "Backtracking",
    estimatedHours: 12,
    subtopics: [
      "Backtracking template",
      "Subsets and combinations",
      "Permutations",
      "Pruning for optimization",
    ],
    resources: [],
    leetcode: [
      { id: 78, title: "Subsets", difficulty: "Medium" },
      { id: 39, title: "Combination Sum", difficulty: "Medium" },
      { id: 46, title: "Permutations", difficulty: "Medium" },
      { id: 90, title: "Subsets II", difficulty: "Medium" },
      { id: 40, title: "Combination Sum II", difficulty: "Medium" },
      { id: 79, title: "Word Search", difficulty: "Medium" },
      { id: 51, title: "N-Queens", difficulty: "Hard" },
      { id: 131, title: "Palindrome Partitioning", difficulty: "Medium" },
      { id: 17, title: "Letter Combinations of Phone Number", difficulty: "Medium" },
    ],
  },

  // ── WEB DEV ───────────────────────────────────────────────
  {
    id: "web-html-css",
    phase: 2,
    category: "Web Development",
    title: "HTML & CSS Fundamentals",
    estimatedHours: 15,
    subtopics: [
      "Semantic HTML tags",
      "CSS box model",
      "Flexbox (master this fully)",
      "CSS Grid",
      "Responsive design + media queries",
      "CSS variables and custom properties",
    ],
    resources: [
      { title: "The Odin Project HTML/CSS", url: "https://www.theodinproject.com/paths/foundations/courses/foundations", type: "website" },
      { title: "Kevin Powell CSS YouTube", url: "https://www.youtube.com/kepowob", type: "youtube" },
      { title: "CSS Tricks Flexbox guide", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "web-js",
    phase: 2,
    category: "Web Development",
    title: "JavaScript Core",
    estimatedHours: 25,
    subtopics: [
      "Variables (var/let/const)",
      "Functions and arrow functions",
      "DOM manipulation",
      "Event listeners",
      "Promises and async/await",
      "fetch API (calling REST APIs)",
      "Array methods (map, filter, reduce)",
      "Destructuring and spread operator",
      "Modules (import/export)",
      "Local storage",
    ],
    resources: [
      { title: "The Odin Project JavaScript", url: "https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript", type: "website" },
      { title: "javascript.info", url: "https://javascript.info/", type: "website" },
      { title: "Traversy Media JS crash course", url: "https://www.youtube.com/c/TraversyMedia", type: "youtube" },
    ],
    leetcode: [],
  },
  {
    id: "web-react",
    phase: 2,
    category: "Web Development",
    title: "React.js",
    estimatedHours: 25,
    subtopics: [
      "JSX syntax",
      "Components (functional)",
      "Props and state (useState)",
      "useEffect hook",
      "useContext for global state",
      "React Router for navigation",
      "Fetching data from APIs in React",
      "Component composition patterns",
      "Error boundaries",
    ],
    resources: [
      { title: "react.dev official docs", url: "https://react.dev/learn", type: "website" },
      { title: "Traversy Media React crash course", url: "https://www.youtube.com/c/TraversyMedia", type: "youtube" },
      { title: "Jack Herrington React YouTube", url: "https://www.youtube.com/@jherr", type: "youtube" },
    ],
    leetcode: [],
  },
  {
    id: "web-fastapi",
    phase: 2,
    category: "Web Development",
    title: "Backend with FastAPI (Python)",
    estimatedHours: 15,
    subtopics: [
      "REST API concepts (GET/POST/PUT/DELETE)",
      "FastAPI setup and routing",
      "Request/response models with Pydantic",
      "Path and query parameters",
      "Database connection (SQLAlchemy + Postgres)",
      "Authentication with JWT tokens",
      "CORS configuration",
      "API documentation with Swagger (auto)",
      "Deployment to Railway/Render",
    ],
    resources: [
      { title: "FastAPI official docs", url: "https://fastapi.tiangolo.com/", type: "website" },
      { title: "Amigoscode FastAPI course", url: "https://www.youtube.com/c/amigoscode", type: "youtube" },
      { title: "TechWithTim FastAPI tutorial", url: "https://www.youtube.com/c/TechWithTim", type: "youtube" },
    ],
    leetcode: [],
  },

  // ── DATABASES ADVANCED ────────────────────────────────────
  {
    id: "db-postgres",
    phase: 2,
    category: "Databases",
    title: "PostgreSQL Deep Dive",
    estimatedHours: 20,
    subtopics: [
      "Advanced JOINs and subqueries",
      "Window functions (ROW_NUMBER, RANK, LAG)",
      "CTEs (Common Table Expressions)",
      "Indexes (B-tree, Hash, partial indexes)",
      "Query optimization and EXPLAIN ANALYZE",
      "Transactions and ACID",
      "Stored procedures and triggers",
    ],
    resources: [
      { title: "Mode SQL Tutorial (advanced)", url: "https://mode.com/sql-tutorial", type: "website" },
      { title: "PostgreSQL official docs", url: "https://www.postgresql.org/docs/", type: "website" },
      { title: "Use The Index Luke", url: "https://use-the-index-luke.com/", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "db-redis",
    phase: 2,
    category: "Databases",
    title: "Redis Basics",
    estimatedHours: 10,
    subtopics: [
      "Key-value store concept",
      "Redis data types (string, list, hash, set)",
      "TTL and expiration",
      "Caching patterns",
      "Session storage with Redis",
    ],
    resources: [
      { title: "Redis University", url: "https://university.redis.io/", type: "course" },
      { title: "TechWithTim Redis tutorial", url: "https://www.youtube.com/c/TechWithTim", type: "youtube" },
    ],
    leetcode: [],
  },

  // ── ML FOUNDATIONS ────────────────────────────────────────
  {
    id: "ml-math",
    phase: 2,
    category: "ML Foundations",
    title: "Math for ML",
    estimatedHours: 20,
    subtopics: [
      "Linear algebra (vectors, matrices, dot product, matrix multiplication)",
      "Calculus (derivatives, chain rule, gradient concept)",
      "Statistics (mean, std, distributions, hypothesis testing)",
      "Probability (Bayes theorem, conditional probability)",
    ],
    resources: [
      { title: "3Blue1Brown Linear Algebra", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab", type: "youtube" },
      { title: "3Blue1Brown Calculus", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr", type: "youtube" },
      { title: "StatQuest with Josh Starmer", url: "https://www.youtube.com/c/joshstarmer", type: "youtube" },
    ],
    leetcode: [],
  },
  {
    id: "ml-numpy-pandas",
    phase: 2,
    category: "ML Foundations",
    title: "NumPy & Pandas",
    estimatedHours: 15,
    subtopics: [
      "NumPy arrays, operations, broadcasting",
      "Array indexing and slicing",
      "DataFrame creation and manipulation",
      "Data cleaning (null handling, duplicates)",
      "Groupby and aggregation",
      "Merging and joining DataFrames",
      "Reading/writing CSV, Excel, JSON",
    ],
    resources: [
      { title: "Corey Schafer Pandas", url: "https://www.youtube.com/c/Coreyms", type: "youtube" },
      { title: "NumPy official quickstart", url: "https://numpy.org/doc/stable/user/quickstart.html", type: "website" },
      { title: "Kaggle micro-courses", url: "https://www.kaggle.com/learn", type: "course" },
    ],
    leetcode: [],
  },
  {
    id: "ml-sklearn",
    phase: 2,
    category: "ML Foundations",
    title: "Scikit-learn & Classical ML",
    estimatedHours: 25,
    subtopics: [
      "ML pipeline (data → train → evaluate)",
      "Linear Regression",
      "Logistic Regression",
      "Decision Trees and Random Forests",
      "SVM basics",
      "K-Means clustering",
      "Train/test split, cross-validation",
      "Evaluation metrics (accuracy, F1, AUC)",
      "Feature engineering basics",
    ],
    resources: [
      { title: "Hands-On ML with Scikit-Learn (book)", url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125974/", type: "book" },
      { title: "Kaggle micro-courses", url: "https://www.kaggle.com/learn", type: "course" },
      { title: "StatQuest ML playlist", url: "https://www.youtube.com/c/joshstarmer", type: "youtube" },
    ],
    leetcode: [],
  },

  // ── PROJECTS PHASE 2 ────────────────────────────────────
  {
    id: "proj-taskmanager",
    phase: 2,
    category: "Projects",
    title: "Project 4: Full-Stack Task Manager",
    estimatedHours: 40,
    subtopics: [
      "FastAPI backend with PostgreSQL",
      "JWT authentication",
      "React frontend",
      "CRUD operations end-to-end",
      "Deploy backend to Railway",
      "Deploy frontend to Vercel",
      "Custom domain setup",
    ],
    resources: [],
    leetcode: [],
  },
  {
    id: "proj-salary",
    phase: 2,
    category: "Projects",
    title: "Project 5: ML Salary Predictor",
    estimatedHours: 40,
    subtopics: [
      "Scrape/use job salary dataset",
      "EDA with pandas + matplotlib",
      "Feature engineering",
      "Train multiple models, compare",
      "Build FastAPI endpoint for predictions",
      "Simple React frontend for predictions",
      "Deploy end-to-end",
    ],
    resources: [],
    leetcode: [],
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 3: PEAK PREP
  // ═══════════════════════════════════════════════════════════

  {
    id: "sd-fundamentals",
    phase: 3,
    category: "System Design",
    title: "System Design Fundamentals",
    estimatedHours: 40,
    subtopics: [
      "How to approach system design interviews",
      "Scalability concepts (vertical vs horizontal)",
      "Load balancing (round robin, least conn)",
      "Caching strategies (write-through, write-behind, cache-aside)",
      "CDN (Content Delivery Network)",
      "Database sharding and partitioning",
      "Replication (master-slave, master-master)",
      "CAP theorem",
      "Consistent hashing",
      "Message queues (Kafka, RabbitMQ concepts)",
    ],
    resources: [
      { title: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer", type: "website" },
      { title: "Gaurav Sen System Design", url: "https://www.youtube.com/c/GauravSensei", type: "youtube" },
      { title: "ByteByteGo YouTube", url: "https://www.youtube.com/@ByteByteGo", type: "youtube" },
      { title: "Designing Data-Intensive Apps (book)", url: "https://dataintensive.net/", type: "book" },
    ],
    leetcode: [],
  },
  {
    id: "sd-real-systems",
    phase: 3,
    category: "System Design",
    title: "Design Real Systems",
    estimatedHours: 40,
    subtopics: [
      "Design URL shortener (like bit.ly)",
      "Design Twitter feed",
      "Design WhatsApp",
      "Design YouTube",
      "Design Uber",
      "Design Netflix recommendation",
      "Design rate limiter",
      "Design distributed cache",
    ],
    resources: [
      { title: "Alex Xu System Design Interview (book)", url: "https://www.amazon.com/System-Design-Interview-insiders-Second/dp/B08CMF2CQF", type: "book" },
      { title: "ByteByteGo newsletter", url: "https://blog.bytebytego.com/", type: "website" },
      { title: "Exponent system design course", url: "https://www.tryexponent.com/courses/system-design-interview", type: "course" },
    ],
    leetcode: [],
  },

  // ── AI & LLM ──────────────────────────────────────────────
  {
    id: "ai-deep-learning",
    phase: 3,
    category: "AI & LLMs",
    title: "Deep Learning Fundamentals",
    estimatedHours: 25,
    subtopics: [
      "Neural network architecture",
      "Activation functions (ReLU, sigmoid, tanh)",
      "Forward and backpropagation",
      "Gradient descent variants (SGD, Adam)",
      "Overfitting and regularization (dropout, L1/L2)",
      "Batch normalization",
      "CNNs (Convolutional Neural Networks)",
      "RNNs and LSTMs (basics)",
    ],
    resources: [
      { title: "Deep Learning Specialization — Andrew Ng", url: "https://www.coursera.org/specializations/deep-learning", type: "course" },
      { title: "3Blue1Brown Neural Networks", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi", type: "youtube" },
      { title: "fast.ai Practical Deep Learning", url: "https://course.fast.ai/", type: "course" },
    ],
    leetcode: [],
  },
  {
    id: "ai-pytorch",
    phase: 3,
    category: "AI & LLMs",
    title: "PyTorch Fundamentals",
    estimatedHours: 20,
    subtopics: [
      "Tensors and operations",
      "Autograd (automatic differentiation)",
      "Building neural networks (nn.Module)",
      "Training loop implementation",
      "DataLoader and Datasets",
      "GPU usage with CUDA",
      "Saving and loading models",
    ],
    resources: [
      { title: "PyTorch official tutorials", url: "https://pytorch.org/tutorials/", type: "website" },
      { title: "Daniel Bourke PyTorch for Deep Learning", url: "https://www.youtube.com/@mrdbourke", type: "youtube" },
    ],
    leetcode: [],
  },
  {
    id: "ai-transformers",
    phase: 3,
    category: "AI & LLMs",
    title: "Transformer Architecture & LLMs",
    estimatedHours: 20,
    subtopics: [
      "Attention mechanism (self-attention)",
      "Multi-head attention",
      "Transformer architecture end-to-end",
      "BERT and GPT architecture differences",
      "Tokenization (BPE, WordPiece)",
      "Fine-tuning pre-trained models",
      "Prompt engineering techniques",
      "LLM evaluation metrics",
    ],
    resources: [
      { title: "Andrej Karpathy 'Let's build GPT'", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", type: "youtube" },
      { title: "'Attention Is All You Need' paper", url: "https://arxiv.org/abs/1706.03762", type: "website" },
      { title: "Hugging Face course", url: "https://huggingface.co/learn/nlp-course", type: "course" },
    ],
    leetcode: [],
  },
  {
    id: "ai-rag",
    phase: 3,
    category: "AI & LLMs",
    title: "RAG Systems",
    estimatedHours: 15,
    subtopics: [
      "Vector embeddings concept",
      "Vector databases (Pinecone, ChromaDB, Weaviate, pgvector)",
      "Semantic search vs keyword search",
      "Chunking strategies for documents",
      "RAG pipeline implementation",
      "Evaluation of RAG systems (RAGAS)",
      "Advanced RAG (HyDE, reranking, multi-query)",
    ],
    resources: [
      { title: "LangChain documentation", url: "https://docs.langchain.com/", type: "website" },
      { title: "LlamaIndex documentation", url: "https://docs.llamaindex.ai/", type: "website" },
      { title: "DeepLearning.ai RAG courses", url: "https://www.deeplearning.ai/short-courses/", type: "course" },
    ],
    leetcode: [],
  },
  {
    id: "ai-agents",
    phase: 3,
    category: "AI & LLMs",
    title: "AI Agents (THE KEY SKILL FOR ₹60L)",
    estimatedHours: 25,
    subtopics: [
      "What agents are vs chatbots",
      "Tool use / function calling",
      "ReAct framework (Reason + Act)",
      "Planning and decomposition",
      "Memory systems (short + long term)",
      "Multi-agent frameworks",
      "Building agents with Claude API",
      "Building agents with LangGraph",
      "Evaluating agent performance",
      "Agentic system safety and guardrails",
    ],
    resources: [
      { title: "Anthropic Claude API docs", url: "https://docs.anthropic.com/", type: "website" },
      { title: "Andrew Ng 'AI Agents in LangGraph'", url: "https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/", type: "course" },
      { title: "LangGraph documentation", url: "https://langchain-ai.github.io/langgraph/", type: "website" },
      { title: "Lilian Weng 'LLM Powered Agents'", url: "https://lilianweng.github.io/posts/2023-06-23-agent/", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "ai-mlops",
    phase: 3,
    category: "AI & LLMs",
    title: "MLOps Basics",
    estimatedHours: 15,
    subtopics: [
      "Model versioning (MLflow)",
      "Experiment tracking",
      "Model serving (FastAPI + Docker)",
      "CI/CD for ML pipelines",
      "Monitoring model performance in prod",
      "A/B testing for models",
    ],
    resources: [
      { title: "Made With ML", url: "https://madewithml.com/", type: "website" },
      { title: "MLflow documentation", url: "https://mlflow.org/docs/latest/index.html", type: "website" },
    ],
    leetcode: [],
  },

  // ── CLOUD & DEVOPS ────────────────────────────────────────
  {
    id: "devops-docker",
    phase: 3,
    category: "Cloud & DevOps",
    title: "Docker",
    estimatedHours: 15,
    subtopics: [
      "What containers are and why",
      "Dockerfile writing",
      "docker build, run, exec commands",
      "Docker volumes and networking",
      "Docker Compose for multi-service apps",
      "Pushing to Docker Hub",
    ],
    resources: [
      { title: "TechWithTim Docker tutorial", url: "https://www.youtube.com/c/TechWithTim", type: "youtube" },
      { title: "Docker official get-started guide", url: "https://docs.docker.com/get-started/", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "devops-aws",
    phase: 3,
    category: "Cloud & DevOps",
    title: "AWS Fundamentals",
    estimatedHours: 25,
    subtopics: [
      "EC2 (virtual machines)",
      "S3 (object storage)",
      "RDS (managed databases)",
      "Lambda (serverless functions)",
      "API Gateway",
      "IAM (Identity and Access Management)",
      "CloudWatch (monitoring)",
      "Route 53 (DNS)",
      "VPC basics",
    ],
    resources: [
      { title: "AWS Cloud Practitioner prep", url: "https://aws.amazon.com/certification/certified-cloud-practitioner/", type: "course" },
      { title: "FreeCodeCamp AWS course", url: "https://www.youtube.com/c/Freecodecamp", type: "youtube" },
      { title: "AWS documentation", url: "https://docs.aws.amazon.com/", type: "website" },
    ],
    leetcode: [],
  },

  // ── PROJECTS PHASE 3 ────────────────────────────────────
  {
    id: "proj-research-bot",
    phase: 3,
    category: "Projects",
    title: "Project 6: AI Agent — Personal Research Bot",
    estimatedHours: 40,
    subtopics: [
      "Takes a research topic as input",
      "Uses Claude API with tool use",
      "Tools: web search, PDF reader, Wikipedia API, arxiv API",
      "Synthesizes findings into a report",
      "Stores reports in vector DB for future",
      "React frontend with streaming output",
      "Deploy on Vercel + Railway",
    ],
    resources: [],
    leetcode: [],
  },
  {
    id: "proj-codebase-qa",
    phase: 3,
    category: "Projects",
    title: "Project 7: RAG-powered Codebase Q&A",
    estimatedHours: 30,
    subtopics: [
      "Index a GitHub repo into vector DB",
      "Ask questions about the codebase",
      "Returns answers with file + line refs",
      "Works with any public GitHub URL",
      "Streaming responses",
      "Claude API for generation",
    ],
    resources: [],
    leetcode: [],
  },
  {
    id: "proj-saas",
    phase: 3,
    category: "Projects",
    title: "Project 8: Full-Stack SaaS (Micro)",
    estimatedHours: 30,
    subtopics: [
      "Pick a real problem you face",
      "Landing page + auth + dashboard",
      "Stripe payment integration",
      "One core AI feature using Claude",
      "Deploy and get 10 real users",
    ],
    resources: [],
    leetcode: [],
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 4: APPLICATION BLITZ
  // ═══════════════════════════════════════════════════════════

  {
    id: "grind-advanced-lc",
    phase: 4,
    category: "Interview Prep",
    title: "Advanced LC Patterns (Grind)",
    estimatedHours: 100,
    subtopics: [
      "Hard graph problems (30 problems)",
      "Hard DP problems (30 problems)",
      "Hard string problems (20 problems)",
      "Bit manipulation (10 problems)",
      "Math problems (10 problems)",
      "Amazon: 50 most asked",
      "Microsoft: 50 most asked",
      "Flipkart: 30 most asked",
    ],
    resources: [
      { title: "NeetCode 150", url: "https://neetcode.io/practice", type: "website" },
      { title: "Striver SDE Sheet", url: "https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/", type: "website" },
      { title: "Blind 75", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "prep-behavioural",
    phase: 4,
    category: "Interview Prep",
    title: "Behavioural Interview Prep",
    estimatedHours: 15,
    subtopics: [
      "STAR method (Situation, Task, Action, Result)",
      "'Tell me about yourself' (2 min pitch)",
      "'Why do you want to work here?'",
      "Greatest strength/weakness answers",
      "Conflict resolution story",
      "Leadership story",
      "Failure story (what you learned)",
      "Impact story (quantified results)",
    ],
    resources: [
      { title: "Jeff H Sipe behavioural interview", url: "https://www.youtube.com/@JeffHSipe", type: "youtube" },
      { title: "Cracking the Coding Interview (behavioural)", url: "https://www.crackingthecodinginterview.com/", type: "book" },
    ],
    leetcode: [],
  },
  {
    id: "prep-resume",
    phase: 4,
    category: "Interview Prep",
    title: "Resume & LinkedIn Optimization",
    estimatedHours: 10,
    subtopics: [
      "1-page resume (ATS-friendly format)",
      "Quantify every bullet (numbers, %)",
      "Projects section (GitHub links, live URLs)",
      "Skills section (right keywords)",
      "LinkedIn: banner, headline, about section",
      "LinkedIn: get 500+ connections strategy",
      "Cold outreach message templates",
      "Alumni network activation (MVIT seniors)",
    ],
    resources: [
      { title: "Exponent resume guide", url: "https://www.tryexponent.com/", type: "website" },
      { title: "Resume Worded", url: "https://resumeworded.com/", type: "website" },
      { title: "TechInterviewHandbook", url: "https://www.techinterviewhandbook.org/resume/", type: "website" },
    ],
    leetcode: [],
  },
  {
    id: "prep-sysdesign",
    phase: 4,
    category: "Interview Prep",
    title: "System Design Interview Practice",
    estimatedHours: 30,
    subtopics: [
      "30 mock system design sessions",
      "Practice with timer (45 min per question)",
      "Record yourself and review",
      "Get feedback from online communities",
    ],
    resources: [
      { title: "Pramp (free mock interviews)", url: "https://www.pramp.com/", type: "website" },
      { title: "Interviewing.io", url: "https://interviewing.io/", type: "website" },
      { title: "ExponentHQ system design course", url: "https://www.tryexponent.com/courses/system-design-interview", type: "course" },
    ],
    leetcode: [],
  },
  {
    id: "prep-negotiation",
    phase: 4,
    category: "Interview Prep",
    title: "Offer Negotiation",
    estimatedHours: 5,
    subtopics: [
      "Never accept first offer",
      "Competing offer leverage strategy",
      "How to negotiate base vs equity vs bonus",
      "How to evaluate total comp (not just base)",
      "Counter-offer scripts",
      "How cousin's referrals affect negotiation",
    ],
    resources: [
      { title: "Levels.fyi for salary data", url: "https://www.levels.fyi/", type: "website" },
      { title: "Gergely Orosz salary negotiation guide", url: "https://blog.pragmaticengineer.com/", type: "website" },
      { title: "Haseeb Qureshi negotiation blog", url: "https://haseebq.com/my-ten-rules-for-negotiating-a-job-offer/", type: "website" },
    ],
    leetcode: [],
  },
];
